export const stackSection = {
  id: 'stack',
  lightBg: false,
  lightText: true,
  topLine: 'Umiejętności',
  headline: 'Lorem ipsum dolor sit amet.',
  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, quibusdam! Nisi, quidem. Alias, doloremque.',
  buttonLabel: 'Wyślij',
  imgStart: false,
  img: require('../../assets/images/stack.svg').default,
  alt: 'stack',
  darkbtnfont: true,
  primarybtn: true,
  darkTextDesc: false,
};
export const projectsSection = {
  id: 'projects',
  lightBg: true,
  lightText: false,
  topLine: 'Projekty',
  headline: 'Lorem ipsum dolor sit amet.',
  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, quibusdam! Nisi, quidem. Alias, doloremque.',
  buttonLabel: 'Wyślij',
  imgStart: true,
  img: require('../../assets/images/projects.svg').default,
  alt: 'projects',
  darkbtnfont: false,
  primarybtn: false,
  darkTextDesc: true,
};

export const contactSection = {
  id: 'contact',
  lightBg: true,
  lightText: false,
  topLine: 'Kontakt',
  headline: 'Lorem ipsum dolor sit amet.',
  description: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quo, quibusdam! Nisi, quidem. Alias, doloremque.',
  buttonLabel: 'Wyślij',
  imgStart: false,
  img: require('../../assets/images/contact.svg').default,
  alt: 'contact',
  darkbtnfont: false,
  primarybtn: false,
  darkTextDesc: true,
};
